#!/usr/bin/env python3
"""Compile exclusive_ca/allowlist.json into exclusive_ca_data.inc."""

from __future__ import annotations

import argparse
import json
import sys


def parse_hex32(value: str) -> bytes:
    raw = bytes.fromhex(value.strip().lower().replace(":", ""))
    if len(raw) != 32:
        raise ValueError(f"expected 32-byte sha256, got {len(raw)} for {value!r}")
    return raw


def c_array(data: bytes) -> str:
    return "{" + ", ".join(f"0x{b:02x}" for b in data) + "}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("allowlist_json")
    args = parser.parse_args()

    data = json.load(open(args.allowlist_json, encoding="utf-8"))
    roots = data.get("roots") or []
    spkis = []
    names = []
    for root in roots:
        spki = root.get("spki_sha256")
        if not spki:
            print(f"skip {root.get('common_name')}: missing spki", file=sys.stderr)
            continue
        spkis.append(parse_hex32(spki))
        names.append(root.get("common_name") or "unknown")

    enabled = bool(data.get("enabled_by_default", False))
    print("// Generated by tools/gen_exclusive_ca_inc.py — do not edit by hand.")
    print("#include <stddef.h>")
    print("#include <stdint.h>")
    print()
    print("namespace vanadium {")
    print("namespace exclusive_ca {")
    print("namespace data {")
    print()
    print(f"constexpr bool kEnabled = {'true' if enabled else 'false'};")
    print(f"constexpr size_t kSpkiCount = {len(spkis)};")
    if spkis:
        print("constexpr uint8_t kAllowedSpkis[][32] = {")
        for spki, name in zip(spkis, names):
            print(f"  // {name}")
            print(f"  {c_array(spki)},")
        print("};")
    else:
        print("constexpr uint8_t kAllowedSpkis[][32] = {{0}};")
    print()
    print("}  // namespace data")
    print("}  // namespace exclusive_ca")
    print("}  // namespace vanadium")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
