#!/usr/bin/env python3
"""Compile denylist/china-related-cas.json into china_denylist_data.inc (SPKI hashes)."""

from __future__ import annotations

import argparse
import json
import sys


def parse_hex32(value: str) -> bytes:
    raw = bytes.fromhex(value.strip().lower().replace(":", ""))
    if len(raw) != 32:
        raise ValueError(f"expected 32-byte sha256, got {len(raw)} for {value!r}")
    return raw


def c_array(data: bytes) -> str:
    return "{" + ", ".join(f"0x{b:02x}" for b in data) + "}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("denylist_json")
    args = parser.parse_args()

    data = json.load(open(args.denylist_json, encoding="utf-8"))
    roots = data.get("roots") or []
    spkis = []
    names = []
    for root in roots:
        spki = root.get("spki_sha256")
        if not spki:
            print(f"skip {root.get('common_name')}: missing spki", file=sys.stderr)
            continue
        spkis.append(parse_hex32(spki))
        names.append(root.get("common_name") or "unknown")

    print("// Generated by tools/gen_china_denylist_inc.py — do not edit by hand.")
    print("#include <stddef.h>")
    print("#include <stdint.h>")
    print()
    print("namespace vanadium {")
    print("namespace china_denylist {")
    print("namespace data {")
    print()
    print(f"constexpr bool kEnabled = {'true' if data.get('enabled_by_default', True) else 'false'};")
    print(f"constexpr size_t kSpkiCount = {len(spkis)};")
    print("constexpr uint8_t kDeniedSpkis[][32] = {")
    for spki, name in zip(spkis, names):
        print(f"  // {name}")
        print(f"  {c_array(spki)},")
    print("};")
    print()
    print("}  // namespace data")
    print("}  // namespace china_denylist")
    print("}  // namespace vanadium")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
