#!/usr/bin/env python3
"""Compile whitelist_pins/policy.json into whitelist_pins_data.inc."""

from __future__ import annotations

import argparse
import base64
import json
import sys


def parse_sha256(token: str) -> bytes:
    token = token.strip()
    if not token.startswith("sha256/"):
        raise ValueError(f"expected sha256/<b64>, got {token!r}")
    raw = base64.b64decode(token[len("sha256/") :])
    if len(raw) != 32:
        raise ValueError(f"bad sha256 length for {token!r}")
    return raw


def bytes_as_c_array(data: bytes) -> str:
    return "{" + ", ".join(f"0x{b:02x}" for b in data) + "}"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("policy_json")
    args = parser.parse_args()

    policy = json.load(open(args.policy_json, encoding="utf-8"))
    hosts = policy.get("hosts") or []

    print("// Generated by tools/gen_whitelist_pins_inc.py — do not edit by hand.")
    print("#include <stddef.h>")
    print("#include <stdint.h>")
    print()
    print("namespace vanadium {")
    print("namespace whitelist_pins {")
    print("namespace data {")
    print()

    for hi, host in enumerate(hosts):
        name = host["name"]
        leaves = [parse_sha256(x) for x in host.get("leafSpkiSha256") or []]
        ints = [parse_sha256(x) for x in host.get("intermediateSpkiSha256") or []]
        if not leaves or not ints:
            raise SystemExit(f"host {name}: need both leaf and intermediate pins")

        print(f"constexpr uint8_t kLeaf_{hi}[][32] = {{")
        for leaf in leaves:
            print(f"  {bytes_as_c_array(leaf)},")
        print("};")
        print(f"constexpr size_t kLeafCount_{hi} = {len(leaves)};")
        print(f"constexpr uint8_t kIntermediate_{hi}[][32] = {{")
        for intermediate in ints:
            print(f"  {bytes_as_c_array(intermediate)},")
        print("};")
        print(f"constexpr size_t kIntermediateCount_{hi} = {len(ints)};")
        print()

    print("struct HostPinEntry {")
    print("  const char* host;")
    print("  bool include_subdomains;")
    print("  const uint8_t (*leaf_pins)[32];")
    print("  size_t leaf_count;")
    print("  const uint8_t (*intermediate_pins)[32];")
    print("  size_t intermediate_count;")
    print("};")
    print()
    print(f"constexpr HostPinEntry kHosts[] = {{")
    for hi, host in enumerate(hosts):
        inc = "true" if host.get("include_subdomains") else "false"
        print(
            f'  {{"{host["name"]}", {inc}, kLeaf_{hi}, kLeafCount_{hi}, '
            f"kIntermediate_{hi}, kIntermediateCount_{hi}}},"
        )
    print("};")
    print(f"constexpr size_t kHostCount = {len(hosts)};")
    print()
    print("}  // namespace data")
    print("}  // namespace whitelist_pins")
    print("}  // namespace vanadium")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
