#!/usr/bin/env python3
"""Compile denylist/*-related-cas.json into china_denylist_data.inc (multi-country SPKIs).

Keeps the existing china_denylist C++ namespace / include path so patch 0290
call sites stay stable; data.inc now embeds CN/MY/SG/ES/RU/IR + DigiCert TLS CN lists.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


COUNTRIES = (
    ("china", "china-related-cas.json"),
    ("malaysia", "malaysia-related-cas.json"),
    ("singapore", "singapore-related-cas.json"),
    ("spain", "spain-related-cas.json"),
    ("russia", "russia-related-cas.json"),
    ("iran", "iran-related-cas.json"),
    ("digicert_tls_cn", "digicert-tls-cn-intermediates.json"),
)


def parse_hex32(value: str) -> bytes:
    raw = bytes.fromhex(value.strip().lower().replace(":", ""))
    if len(raw) != 32:
        raise ValueError(f"expected 32-byte sha256, got {len(raw)} for {value!r}")
    return raw


def c_array(data: bytes) -> str:
    return "{" + ", ".join(f"0x{b:02x}" for b in data) + "}"


def load_roots(path: Path) -> tuple[bool, list[tuple[str, bytes]]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    enabled = bool(data.get("enabled_by_default", True))
    items: list[tuple[str, bytes]] = []
    for root in data.get("roots") or []:
        spki = root.get("spki_sha256")
        if not spki:
            print(f"skip {path.name}/{root.get('common_name')}: missing spki", file=sys.stderr)
            continue
        items.append((root.get("common_name") or "unknown", parse_hex32(spki)))
    return enabled, items


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "denylist_dir",
        nargs="?",
        default="denylist",
        help="Directory containing *-related-cas.json",
    )
    args = parser.parse_args()
    base = Path(args.denylist_dir)

    packs = []
    for key, filename in COUNTRIES:
        path = base / filename
        if not path.exists():
            print(f"missing {path}", file=sys.stderr)
            return 1
        enabled, items = load_roots(path)
        packs.append((key, enabled, items))

    print("// Generated by tools/gen_country_denylist_inc.py — do not edit by hand.")
    print("#include <stddef.h>")
    print("#include <stdint.h>")
    print()
    print("namespace vanadium {")
    print("namespace china_denylist {")
    print("namespace data {")
    print()

    for key, enabled, items in packs:
        print(f"namespace {key} {{")
        print(f"constexpr bool kEnabled = {'true' if enabled else 'false'};")
        print(f"constexpr size_t kSpkiCount = {len(items)};")
        if items:
            print("constexpr uint8_t kDeniedSpkis[][32] = {")
            for name, spki in items:
                print(f"  // {name}")
                print(f"  {c_array(spki)},")
            print("};")
        else:
            # Keep a non-empty array to avoid zero-length array edge cases.
            print("constexpr uint8_t kDeniedSpkis[][32] = {{0}};")
        print(f"}}  // namespace {key}")
        print()

    # Back-compat aliases used by older china-only checkers.
    china_enabled = next(e for k, e, _ in packs if k == "china")
    china_items = next(items for k, _, items in packs if k == "china")
    print(f"constexpr bool kEnabled = {'true' if china_enabled else 'false'};")
    print(f"constexpr size_t kSpkiCount = {len(china_items)};")
    print("constexpr uint8_t kDeniedSpkis[][32] = {")
    for name, spki in china_items:
        print(f"  // {name}")
        print(f"  {c_array(spki)},")
    if not china_items:
        print("  {0},")
    print("};")
    print()
    print("}  // namespace data")
    print("}  // namespace china_denylist")
    print("}  // namespace vanadium")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
